### ISSUE TITLE
viridis command hangs the CPU at 100%

### ISSUE THREAD

**Issue by thatchermo** [sjmgarnier/viridisLite#19] opened 2020-06-19 21:36 UTC
I thought I'd pass this maddening bug on, although I don't know if it really is a problem with this package itself. More an information item in case anyone else runs into this or knows where to take it next. I first reported it as a [bug with ggplot](https://github.com/tidyverse/ggplot2/issues/4054#issue-635370259). A partial quote from that bug:

- I'm running Ubuntu 20.04, with R 4.0.1. If I run `library(viridisLite); viridis(10)` from R running in a terminal window, the CPU goes to 100% and the process hangs, but...

- Those commands work for me when executed from RStudio's console on the same computer. They also work when executed on a clean install of Ubuntu 20.04, with R 4.0.1 and a clean install of the viridisLite package.

- Looking at the code for the `viridis` command from that package, if I type the code in manually as shown below, it hangs at the invocation of `fn_cols`. Doesn't matter if I replace `spline` with `linear` in the `colorRamp` command. Some code works fine on a fresh install.

```
library(viridisLite)
n=10; alpha = 1; begin = 0; end = 1; direction = 1; option = "D"
if (begin < 0 | begin > 1 | end < 0 | end > 1) {
        stop("begin and end must be in [0,1]")
}
if (abs(direction) != 1) {
    stop("direction must be 1 or -1")
}
if (direction == -1) {
    tmp <- begin
    begin <- end
    end <- tmp
}
option <- switch(EXPR = option, A = "A", magma = "A", B = "B",
    inferno = "B", C = "C", plasma = "C", D = "D", viridis = "D",
    E = "E", cividis = "E", {
        warning(paste0("Option '", option, "' does not exist. Defaulting to 'viridis'."))
        "D"
    })
map <- viridisLite::viridis.map[viridisLite::viridis.map$opt ==
    option, ]
map_cols <- grDevices::rgb(map$R, map$G, map$B)
fn_cols <- grDevices::colorRamp(map_cols, space = "Lab",
    interpolate = "spline")
# Hangs at the next line!
cols <- fn_cols(seq(begin, end, length.out = n))/255
grDevices::rgb(cols[, 1], cols[, 2], cols[, 3], alpha = alpha)
```
- Replacing the `space="Lab"` option with `space="rgb"` option yields code that runs and (oddly?) produces the same output as `viridis(10)` on a system where that command works.

- So function `fn_cols` seems to be created OK, but that function itself hangs when called. And that's as far as I've had energy to trace it at the moment. Next step would be to look at how the conversion to Lab and the interpolation breaks down?

- It wouldn't be so bad if I didn't use the viridis scales all the time! Will I reinstall the whole operating system to see if it will fix this problem? Just maybe, but I'd rather figure it out.

**Comment by sjmgarnier** [comment] 2021-04-11 18:09
@thatchermo I finally found the time to update `viridis(Lite)`. Unfortunately, I could not reproduce this bug. Could the issue be with an old version of `grDevices` on your system? That might explain why the problem doesn't appear on a clean install.

**Comment by thatchermo** [comment] 2021-04-12 15:41
Not sure I can be a lot more help at this point, since the offending
combination of versions is long gone on my computers at this point, but I'm
not worried about it either. If memory serves, it was a bug that was triggered
just by interpolating between values, and I traced it as far as commands that
didn't involve display, but just interpolation, and I could reproduce it by
running those commands directly. Made me think it was something pretty low
level that was triggering by the actual math being done or the interface from
one library into another maybe changing over time and causing the crash.
That's pretty vague, but I was satisfied that it wasn't really a problem with
any of the viridis Lite code at the end of the day--at least that's what my
memory says. And it disappeared when the whole computer was brought up to
date. I'm happy to consider it closed.

Scott Thatcher

On Sun, Apr 11, 2021 at 11:09:29AM -0700, Simon Garnier wrote:
> @thatchermo I finally found the time to update `viridis(Lite)`. Unfortunately, I could not reproduce this bug. Could the issue be with an old version of `grDevices` on your system? That might explain why the problem doesn't appear on a clean install.  
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/sjmgarnier/viridisLite/issues/19#issuecomment-817348357

-- 
Scott Thatcher
Associate Professor of Statistics
Truman State University
***@***.***

**Comment by sjmgarnier** [comment] 2021-04-12 15:49
@thatchermo Great, thanks. Closing now then.

**Closed as completed by sjmgarnier** 2021-04-12 15:49 UTC
